sudo: false
dist: trusty

addons:
  apt:
    packages:
      - git-crypt

before_install: |
  openssl aes-256-cbc -K $encrypted_3dc41751ea19_key -iv $encrypted_3dc41751ea19_iv -in git-crypt.key.enc -out git-crypt.key -d
  git-crypt unlock git-crypt.key
  rm git-crypt.key

install: |
  mkdir -p /tmp/packer
  cd /tmp/packer
  curl -o packer.zip https://releases.hashicorp.com/packer/0.10.0/packer_0.10.0_linux_amd64.zip
  unzip packer.zip
  rm packer.zip

script: |
  export PATH=$PATH:/tmp/packer
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    export AWS_ENV="prod"
  else
    export AWS_ENV="dev"
  fi

  cd ami
  version="$TRAVIS_BRANCH @ $(echo $TRAVIS_COMMIT | cut -c 1-7)"
  packer build -var="env=$AWS_ENV" -var="version=$VERSION" -var-file="variables.$AWS_ENV.json" packer.json

