- name: Upgrade logspout-goodeggs
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: "docker_image_tag"
      prompt: "Docker Image Tag?"
      default: "dev"
      private: no
  tasks:
    - name: Update /etc/logspout-goodeggs/image
      become: true
      copy:
        content: "goodeggs/logspout-goodeggs:{{ docker_image_tag }}"
        dest: /etc/logspout-goodeggs/image
        owner: root
        mode: 0400
    - name: Restart logspout-goodeggs
      become: true
      service:
        name: logspout-goodeggs
        state: restarted

